### PR TITLE
Expand the usage doc to include load/store

### PR DESCRIPTION
**Pull request by romeara**

### CODE REVIEW

**Review by nickavv — COMMENTED** [review]
Since I personally (and likely many people) will be using the gradle plugin to store their credentials, I would like to see documented the format of the credentials.properties file. Are the keys just "username" and "password"? There's no reason not to reduce ambiguity with these kind of docs

**Review by nickavv — COMMENTED** [review]
Honestly given the use of public and private keys, it would probably be useful to have information about how to generate those as well as basic information about where to store them, how to treat them, etc.
We should assume users have no knowledge of security practices. They've come here because they want to do better, but we shouldn't scare them off by making them think "ah screw it plaintext is just so much easier"

It kind of seems like these docs should be on a linked wiki page even since they're getting fairly long.

**Comment by romeara** [comment]
I can integrate the documents with the markdown. How about the top level gets pared down to "what you do with each", which a link to specific usage information?

**Comment by nickavv** [comment]
That's exactly what I think it should look like. The top level says "we have java, cli, and gradle plugins, and here's why they exist!" then links to more detailed usage

**Comment by romeara** [comment]
Alright, shall update the PR

**Comment by nickavv** [comment]
your doc for the gradle plugin doesn't specify a lookup key, so running it as-is will fail. Is that supposed to be part of the properties file too?

EDIT: I see from looking at the code that it's a -P argument at the command line. I've never seen that on a gradle task before, definitely document that bad boy

**Comment by romeara** [comment]
@nickavv Updated let me know how that looks

**Comment by nickavv** [comment]
I think this is good for now. I still feel like there is more I want clarified and that a total novice coming in might still give up before they figured out what they were doing, but I can't figure out exactly what changes I want made so for now lets merge in what you've got

**Comment by nickavv** [comment]
Wait one more thing, can we get a link to the github releases page from the lockdown-cli readme?

**Comment by romeara** [comment]
Good idea, one moment shall add

**Review by nickavv — APPROVED** [review]

**Pull request merged**
